title: Training pipeline for Ancient Greek Language Model
description: >
  Reproducible workflows for training the ancient greek spaCy pipeline.

vars:
  config_trf: "transformer"
  lang: "grc"
  model_name: "grc_core_treebanks"
  gpu: 0
  package_version: "0.0.0"
  spacy_version: ">=3.0.0"

directories: ["assets", "corpus", "training", "scripts"]

workflows:
  fetch_assets:
    - get_pretraining
    - get_treebanks
    - get_named_entities
  preprocess:
    - install
    - get_treebanks
    - get_pretraining
    - get_named_entities
    - parse
    - convert

commands:
  - name: install
    help: "Install dependencies."
    script:
     - "pip install -r requirements.txt"
    deps:
     - "requirements.txt"
  - name: get_treebanks
    help: "Downloads and cleans treebank data."
    script:
     - "bash scripts/fetch_treebanks.sh"
     - "bash scripts/clean_treebanks.sh"
     - "python3 scripts/join_treebanks.py"
  - name: get_pretraining
    help: "Downloads and cleans pretraining data."
    script:
     - "bash scripts/fetch_pretraining.sh"
     - "bash scripts/clean_pretraining.sh"
  - name: get_named_entities
    help: "Downloads and cleans named entity assets."
    script:
     - "bash scripts/fetch_named_entities.sh"
     - "bash scripts/clean_named_entities.sh"
     - "python3 scripts/prepare_named_entities.py"
  - name: parse
    help: "Parses pretraining dataset."
    script:
      - "python3 scripts/parse_pretraining_corpus.py"
  - name: convert
    help: "Convert CONLL-U files to spacy binaries."
    script:
     - "python3 -m spacy convert assets/treebanks/joint/train.conllu corpus/ --converter conllu -n 10 "
     - "python3 -m spacy convert assets/treebanks/joint/dev.conllu corpus/ --converter conllu -n 10"
     - "python3 -m spacy convert assets/treebanks/joint/test.conllu corpus/ --converter conllu -n 10"
  - name: train_cpu
    help: "Trains a CPU model over the dataset"
    script:
     - "python3 -m spacy train configs/cpu.cfg --output training/${model_name}_sm --paths.train corpus/train.spacy --paths.dev corpus/dev.spacy"
  - name: train_trf
    help: "Finetunes the Bert based transformer model on the treebanks"
    script:
     - "python3 -m spacy train configs/transformer.cfg --output training/${model_name}_trf --paths.train corpus/train.spacy --paths.dev corpus/dev.spacy"